### ISSUE TITLE
Unclear about the model used for MNIST and FashionMNIST

### ISSUE THREAD

**Issue by sairaamVenkatraman** [brjathu/deepcaps#1]
Hi. Thank you for uploading your code. 
Could you please clarify the architecture you used for MNIST and FashionMNIST. Is it the same as the one used for CIFAR-10 and SVHN?
Thank you

**Comment by brjathu** [comment]
Hi, Thanks for the question. Yes, the architecture is same except the fact that the decoder will generate 28*28 gray scale images now. I have updated the code with new model, please check.

**Comment by sairaamVenkatraman** [comment]
Thanks a lot! You guys are amazing!
