### ISSUE TITLE
ensemble.py fails with: No such file or directory: 'deepcaps_1.npy'

### ISSUE THREAD

**Issue by grische** [brjathu/deepcaps#11]
There seem to be some outdated code in `ensemble.py` which causes it to fail towards the end:

```` 
Traceback (most recent call last):
  File "ensemble.py", line 96, in <module>
    d1 = np.load("deepcaps_1.npy")
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/numpy/lib/npyio.py", line 428, in load
    fid = open(os_fspath(file), "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'deepcaps_1.npy'
```

**Comment by brjathu** [comment]
Hi, the path was not correct. Added the prefix to the npy file ("model/CIFAR10/deepcaps_1.npy"). Hope it should be ok now?

**Comment by grische** [comment]
@brjathu almost. I added a PR to fix the missing "d8" and "d9" which are not part of the pretrained sample set you provide :)

**Comment by brjathu** [comment]
Thank you very much. I will merge them.
